repos:
  # Autoformat: Python code
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.3.1
    hooks:
      - id: black

  # Autoformat: markdown, yaml
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.8.1
    hooks:
      - id: prettier

  # `pre-commit sample-config` default hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Lint: Dockerfile
  - repo: https://github.com/hadolint/hadolint.git
    rev: v2.14.0
    hooks:
      - id: hadolint-docker
        entry: hadolint/hadolint:v2.14.0 hadolint

  # Lint: Python
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: [
            # default black line length is 88
            --max-line-length=88,
          ]

    # Static security analysis of GitHub actions https://github.com/woodruffw/zizmor
  # Additional config is in .github/zizmor.yml
  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.23.1
    hooks:
      - id: zizmor
        args:
          - --fix=safe
